execute pathogen#infect()
call pathogen#helptags()
syntax on
" highlight all search matches
set hlsearch
filetype plugin indent on

" show and format status line
set laststatus=2

" Format the status line
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l}

" set theme for airline, comment it out to let plugin chose theme
" based upon currently selected color scheme
" let g:airline_theme='luna'

" GUI font
if has("mac") || has("macunix")
    set gfn=Source\ Code\ Pro\ Light:h13,Menlo:h13
endif

" colorscheme based on time of the day
colorscheme solarized
if strftime("%H") > 18
    set background=dark
elseif strftime("%H") < 7
    set background=dark
else
    set background=light
endif

" tab related
" set tab to 4 spaces
set tabstop=4
" replace tab with spaces
set expandtab
set shiftwidth=4
set softtabstop=4

" map leader to comma instead of backslash
let mapleader = ","

" disable swap and backup files
set nobackup       " no backup files
set nowritebackup  " only in case you don't want a backup file while editing
set noswapfile     " no swap files
set guioptions-=T  " no toolbar
set guioptions-=r  " no scrollbar
